project10_guests: project10_guests.o guest.o read_line.o
	gcc -o project10_guests project10_guests.o guest.o read_line.o

project10_guests.o: project10_guests.c
	gcc -c project10_guests.c

guest.o: guest.c
	gcc -c guest.c

read_line.o: read_line.c
	gcc -c read_line.c